# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividad', '0002_ciudadano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='organismo',
            field=models.CharField(max_length=30),
        ),
    ]
