# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividad', '0003_auto_20160730_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('documentacion', models.TextField()),
                ('recompensa', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='title',
            field=models.CharField(default=b'blah', max_length=20),
        ),
    ]
