# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 14:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Actividad', '0004_auto_20160730_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='acti',
            name='organismo',
            field=models.CharField(default=datetime.datetime(2016, 7, 30, 14, 55, 54, 411000, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
