# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Actividad', '0005_acti_organismo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ciudadano',
            new_name='Usuario',
        ),
    ]
