# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Actividad', '0007_auto_20160730_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='title',
        ),
    ]
