# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividad', '0008_remove_usuario_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='title',
            field=models.CharField(default=b'user1', max_length=90),
        ),
    ]
