# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividad', '0009_usuario_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sedesol', models.PositiveIntegerField()),
                ('sre', models.PositiveIntegerField()),
                ('setravi', models.PositiveIntegerField()),
                ('sat', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='monedas',
            field=models.PositiveIntegerField(),
        ),
    ]
