# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividad', '0010_auto_20160730_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'depto1', max_length=90)),
                ('monedasMaximas', models.PositiveIntegerField(default=999)),
                ('monedasDadas', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Administracion',
        ),
    ]
