# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividad', '0011_auto_20160730_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='title',
            field=models.CharField(default='depto1', max_length=90),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='title',
            field=models.CharField(default='user1', max_length=90),
        ),
    ]
