# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividad', '0012_auto_20160730_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='acti',
            name='identificacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='curp',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
