# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividad', '0014_historialdevisitas_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='acti',
            name='url',
            field=models.CharField(default='www.google.com', max_length=200),
        ),
    ]
