# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Actividad', '0015_acti_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaPremios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(default='user1', max_length=90)),
                ('concepto', models.CharField(default='user1', max_length=400)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
