# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividad', '0016_historiapremios'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiapremios',
            name='usuario',
            field=models.CharField(default='user1', max_length=90),
        ),
    ]
